const router = require("express").Router();
const chit = require("../services/chit");
const h = (fn) => async (req, res) => { try { res.json(await fn(req)); } catch (e) { res.status(e.status || 500).json({ error: e.message, code: e.code || "ERR" }); } };
router.get ("/route",                h((req) => chit.routeDown(req.query.from, req.query.target)));
router.post("/chits",                h((req) => chit.createChit(req.body)));
router.post("/chits/:id/forward",    h((req) => chit.forwardChit({ chitId: req.params.id, toEntity: req.body.toEntity })));
router.post("/chits/:id/advance",    h((req) => chit.advance({ chitId: req.params.id, to: req.body.to })));
router.get ("/entities/:id/inbox",   h((req) => chit.inbox(req.params.id)));
router.get ("/entities/:id/aggregate", h((req) => chit.aggregate(req.params.id)));
module.exports = router;
