-- migration_b42_assist_qa.sql — assistant Q&A library, DB-backed (single source of truth).
-- The old client-side ASSIST_LIB now lives here; GET /api/assist/questions serves it (context-filtered),
-- and it is the grounding feed for the /api/assist LLM proxy. Idempotent — safe to re-run.
-- Run in Supabase SQL editor (RLS off / service role).

CREATE TABLE IF NOT EXISTS assist_qa (
  id         text PRIMARY KEY,
  context    text[] NOT NULL DEFAULT '{}',
  topics     text[] NOT NULL DEFAULT '{}',
  question   text NOT NULL,
  answer     text NOT NULL,
  fit        text,
  media      jsonb,
  sort       int NOT NULL DEFAULT 100,
  active     boolean NOT NULL DEFAULT true,
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_assist_qa_active ON assist_qa(active);

-- Seed (upsert): the 52 consolidated entries.
INSERT INTO assist_qa (id, context, topics, question, answer, fit, media, sort) VALUES ('fit', ARRAY['welcome','login','register']::text[], ARRAY['fit','suitable','right for me','useful','help my business','should i use','is this for me']::text[], 'Is this right for my business?', 'Chit & Bridge fits businesses that exchange orders or deals with other businesses and want a trustworthy, shared record — supply, trade, services, networks. It may NOT fit if you only need a simple invoice app or a consumer storefront. Tell me your business and I will be honest about the fit.', 'maybe', NULL, 0)
  ON CONFLICT (id) DO UPDATE SET context=EXCLUDED.context, topics=EXCLUDED.topics, question=EXCLUDED.question, answer=EXCLUDED.answer, fit=EXCLUDED.fit, media=EXCLUDED.media, sort=EXCLUDED.sort, active=true, updated_at=now();
INSERT INTO assist_qa (id, context, topics, question, answer, fit, media, sort) VALUES ('trust', ARRAY['*']::text[], ARRAY['trust','reliable','safe','secure','privacy','hacked','lose data']::text[], 'How do I know it is reliable?', 'Your records are yours alone (no other business can see them), every deal keeps a copy for both sides like a signed receipt, and there is a full time-stamped audit trail. We answer the hard questions up front rather than ask you to trust a reputation we have not earned yet.', NULL, NULL, 10)
  ON CONFLICT (id) DO UPDATE SET context=EXCLUDED.context, topics=EXCLUDED.topics, question=EXCLUDED.question, answer=EXCLUDED.answer, fit=EXCLUDED.fit, media=EXCLUDED.media, sort=EXCLUDED.sort, active=true, updated_at=now();
INSERT INTO assist_qa (id, context, topics, question, answer, fit, media, sort) VALUES ('schema', ARRAY['*']::text[], ARRAY['customize','schema','fields','my business','different','flexible','adapt']::text[], 'Can it adapt to my business?', 'Yes. The trustworthy container — the record, your privacy, the audit — stays fixed. What a deal CONTAINS is your schema: your fields, your rules. Same engine, different schema = different behaviour. You configure, you do not write code.', NULL, NULL, 20)
  ON CONFLICT (id) DO UPDATE SET context=EXCLUDED.context, topics=EXCLUDED.topics, question=EXCLUDED.question, answer=EXCLUDED.answer, fit=EXCLUDED.fit, media=EXCLUDED.media, sort=EXCLUDED.sort, active=true, updated_at=now();
INSERT INTO assist_qa (id, context, topics, question, answer, fit, media, sort) VALUES ('coassist', ARRAY['coassists','task']::text[], ARRAY['co-assist','coassist','actor','staff','employee','team','who acts','assign work']::text[], 'What is a co-assist?', 'Anyone — or anything — that acts for you. People now; connectors, devices, process rules and AI agents next. You stay the party; they act for you within your entity''s scope (per-actor limits are coming).', NULL, NULL, 30)
  ON CONFLICT (id) DO UPDATE SET context=EXCLUDED.context, topics=EXCLUDED.topics, question=EXCLUDED.question, answer=EXCLUDED.answer, fit=EXCLUDED.fit, media=EXCLUDED.media, sort=EXCLUDED.sort, active=true, updated_at=now();
INSERT INTO assist_qa (id, context, topics, question, answer, fit, media, sort) VALUES ('chit', ARRAY['compose','order','task']::text[], ARRAY['chit','create order','compose','new order','author','place order','send']::text[], 'What is a chit and how do I make one?', 'A chit is a sealed, shared record of a deal. In Compose you author your own record, then bridge it to a counterparty — each side gets its own copy with its own status.', NULL, NULL, 40)
  ON CONFLICT (id) DO UPDATE SET context=EXCLUDED.context, topics=EXCLUDED.topics, question=EXCLUDED.question, answer=EXCLUDED.answer, fit=EXCLUDED.fit, media=EXCLUDED.media, sort=EXCLUDED.sort, active=true, updated_at=now();
INSERT INTO assist_qa (id, context, topics, question, answer, fit, media, sort) VALUES ('dispute', ARRAY['disputes','task','order']::text[], ARRAY['dispute','disagree','problem with order','wrong','complaint']::text[], 'What if something goes wrong with a deal?', 'Either side can raise a dispute inside the system. It is recorded, both sides see it, and it is resolved on the record — not in a lost email thread.', NULL, NULL, 50)
  ON CONFLICT (id) DO UPDATE SET context=EXCLUDED.context, topics=EXCLUDED.topics, question=EXCLUDED.question, answer=EXCLUDED.answer, fit=EXCLUDED.fit, media=EXCLUDED.media, sort=EXCLUDED.sort, active=true, updated_at=now();
INSERT INTO assist_qa (id, context, topics, question, answer, fit, media, sort) VALUES ('isolation', ARRAY['*']::text[], ARRAY['see my data','other business','private','who can see','competitor','confidential']::text[], 'Can another business see my data?', 'No. Every record is stamped as yours, and the system only ever shows you your own rows. Another business can never see your chits, prices, or history, and you cannot see theirs. It is built into the foundation, the way a bank cannot show your statement to another customer. The only thing ever shared is what you deliberately send.', NULL, NULL, 60)
  ON CONFLICT (id) DO UPDATE SET context=EXCLUDED.context, topics=EXCLUDED.topics, question=EXCLUDED.question, answer=EXCLUDED.answer, fit=EXCLUDED.fit, media=EXCLUDED.media, sort=EXCLUDED.sort, active=true, updated_at=now();
INSERT INTO assist_qa (id, context, topics, question, answer, fit, media, sort) VALUES ('lose', ARRAY['*']::text[], ARRAY['lose my data','half done','incomplete','partial','reliable record','durable']::text[], 'What if it loses data or half-finishes an action?', 'An action that touches several records either completes entirely or cleanly rolls back to where it was — never half-done — the same principle a bank uses so money never vanishes mid-transfer. Your records are a durable, time-stamped history.', NULL, NULL, 70)
  ON CONFLICT (id) DO UPDATE SET context=EXCLUDED.context, topics=EXCLUDED.topics, question=EXCLUDED.question, answer=EXCLUDED.answer, fit=EXCLUDED.fit, media=EXCLUDED.media, sort=EXCLUDED.sort, active=true, updated_at=now();
INSERT INTO assist_qa (id, context, topics, question, answer, fit, media, sort) VALUES ('hacked', ARRAY['*']::text[], ARRAY['hacked','attack','security','encrypted','brute force','password','secure']::text[], 'What if it gets hacked or attacked?', 'Traffic is encrypted (HTTPS). We prove your identity from a signed token on every request, never just take your word for it. Login attempts are rate-limited, injected content cannot run, and internal errors are never leaked. The main thing we ask of you: keep your login private, like a bank PIN.', NULL, NULL, 80)
  ON CONFLICT (id) DO UPDATE SET context=EXCLUDED.context, topics=EXCLUDED.topics, question=EXCLUDED.question, answer=EXCLUDED.answer, fit=EXCLUDED.fit, media=EXCLUDED.media, sort=EXCLUDED.sort, active=true, updated_at=now();
INSERT INTO assist_qa (id, context, topics, question, answer, fit, media, sort) VALUES ('record', ARRAY['*']::text[], ARRAY['who can change','audit','tamper','history','proof','change my deal','receipt']::text[], 'Who can change my deal, and is there a record?', 'Only the rightful party can change a deal, and every action — created, accepted, disputed, completed — is written to a complete, time-stamped history, like a courier tracking log. If there is ever a question about what happened, the record answers it.', NULL, NULL, 90)
  ON CONFLICT (id) DO UPDATE SET context=EXCLUDED.context, topics=EXCLUDED.topics, question=EXCLUDED.question, answer=EXCLUDED.answer, fit=EXCLUDED.fit, media=EXCLUDED.media, sort=EXCLUDED.sort, active=true, updated_at=now();
INSERT INTO assist_qa (id, context, topics, question, answer, fit, media, sort) VALUES ('developer', ARRAY['*']::text[], ARRAY['developer','coding','technical','set up','configure','customize myself']::text[], 'Do I need a developer to make it fit my business?', 'No. The trustworthy container stays fixed; your schema — the fields and rules of a deal — is configuration, not code. You define what a deal carries and the same engine adapts. No developer needed.', NULL, NULL, 100)
  ON CONFLICT (id) DO UPDATE SET context=EXCLUDED.context, topics=EXCLUDED.topics, question=EXCLUDED.question, answer=EXCLUDED.answer, fit=EXCLUDED.fit, media=EXCLUDED.media, sort=EXCLUDED.sort, active=true, updated_at=now();
INSERT INTO assist_qa (id, context, topics, question, answer, fit, media, sort) VALUES ('early', ARRAY['welcome','login','register']::text[], ARRAY['new company','reputation','why trust you','established','track record','startup']::text[], 'You are new — why should I trust you?', 'Honestly, we are early, so we will not ask you to trust a reputation we have not earned yet. Instead we answer the hard questions up front and show the engineering. The foundations — privacy, an honest record, safe failure — are built in from day one, which is the part that is hard to add later.', 'maybe', NULL, 110)
  ON CONFLICT (id) DO UPDATE SET context=EXCLUDED.context, topics=EXCLUDED.topics, question=EXCLUDED.question, answer=EXCLUDED.answer, fit=EXCLUDED.fit, media=EXCLUDED.media, sort=EXCLUDED.sort, active=true, updated_at=now();
INSERT INTO assist_qa (id, context, topics, question, answer, fit, media, sort) VALUES ('notfit', ARRAY['welcome','login','register']::text[], ARRAY['not for me','wrong fit','simple invoice','consumer','retail only','too much']::text[], 'When might this NOT be right for me?', 'If you only need a simple invoice or billing app, or a consumer-facing storefront with no business counterparties, this is probably more than you need. It shines when two or more businesses exchange deals and want a shared, trustworthy record. Tell me your situation and I will be straight with you.', 'no', NULL, 120)
  ON CONFLICT (id) DO UPDATE SET context=EXCLUDED.context, topics=EXCLUDED.topics, question=EXCLUDED.question, answer=EXCLUDED.answer, fit=EXCLUDED.fit, media=EXCLUDED.media, sort=EXCLUDED.sort, active=true, updated_at=now();
INSERT INTO assist_qa (id, context, topics, question, answer, fit, media, sort) VALUES ('uc_timber', ARRAY['*','welcome','login','register']::text[], ARRAY['timber','wood','building materials','hardware','counter sale','yard','plywood']::text[], 'Does it work for a timber or building-materials business?', 'Yes. Your schema carries what a timber deal needs — item, quantity, price, delivery yard — and the same engine handles a quick counter sale, a purchase order to a supplier, or a delivery to a site. Change the fields and the compose form, validation and catalogue follow.', NULL, '{"type":"img","src":"app/assets/usecase-timber.png","caption":"Example: a timber order — screen clip coming."}'::jsonb, 130)
  ON CONFLICT (id) DO UPDATE SET context=EXCLUDED.context, topics=EXCLUDED.topics, question=EXCLUDED.question, answer=EXCLUDED.answer, fit=EXCLUDED.fit, media=EXCLUDED.media, sort=EXCLUDED.sort, active=true, updated_at=now();
INSERT INTO assist_qa (id, context, topics, question, answer, fit, media, sort) VALUES ('uc_pharma', ARRAY['*','welcome','login','register']::text[], ARRAY['pharma','pharmacy','medicine','regulated','batch','expiry','compliance']::text[], 'Does it work for pharma or regulated supply?', 'Yes. Your schema can require batch number and expiry, mark fields mandatory, and the sealed record plus the full audit trail give you the traceability regulated supply needs. Same engine, a stricter schema.', NULL, '{"type":"img","src":"app/assets/usecase-pharma.png","caption":"Example: a pharma supply chit — screen clip coming."}'::jsonb, 140)
  ON CONFLICT (id) DO UPDATE SET context=EXCLUDED.context, topics=EXCLUDED.topics, question=EXCLUDED.question, answer=EXCLUDED.answer, fit=EXCLUDED.fit, media=EXCLUDED.media, sort=EXCLUDED.sort, active=true, updated_at=now();
INSERT INTO assist_qa (id, context, topics, question, answer, fit, media, sort) VALUES ('uc_services', ARRAY['*','welcome','login','register']::text[], ARRAY['service','services','site work','contractor','project','milestone','sla']::text[], 'Does it work for a services or site-work business?', 'Yes. A service deal does not need line-item prices the same way — your schema can carry scope, milestones and timelines instead, and disputes-on-the-record matter most here. Same engine, a services schema.', NULL, '{"type":"img","src":"app/assets/usecase-services.png","caption":"Example: a service request chit — screen clip coming."}'::jsonb, 150)
  ON CONFLICT (id) DO UPDATE SET context=EXCLUDED.context, topics=EXCLUDED.topics, question=EXCLUDED.question, answer=EXCLUDED.answer, fit=EXCLUDED.fit, media=EXCLUDED.media, sort=EXCLUDED.sort, active=true, updated_at=now();
INSERT INTO assist_qa (id, context, topics, question, answer, fit, media, sort) VALUES ('uc_aggregator', ARRAY['*','welcome','login','register']::text[], ARRAY['aggregator','network','group','branches','head office','franchise','parent']::text[], 'Does it work for an aggregator or a group with branches?', 'Yes. Network lets you arrange your branches or members as a tree under a top node, and deals can flow down that structure. Each node keeps its own record; the top node sees its own subtree. Same engine, your structure.', NULL, '{"type":"img","src":"app/assets/usecase-aggregator.png","caption":"Example: a network tree — screen clip coming."}'::jsonb, 160)
  ON CONFLICT (id) DO UPDATE SET context=EXCLUDED.context, topics=EXCLUDED.topics, question=EXCLUDED.question, answer=EXCLUDED.answer, fit=EXCLUDED.fit, media=EXCLUDED.media, sort=EXCLUDED.sort, active=true, updated_at=now();
INSERT INTO assist_qa (id, context, topics, question, answer, fit, media, sort) VALUES ('uc_compare', ARRAY['*','welcome','login','register']::text[], ARRAY['different businesses','same product','how does it adapt','one tool','verticals']::text[], 'How can one tool fit very different businesses?', 'The container is the same for everyone — the sealed record, your privacy, the audit. What differs is the schema. A timber yard and a pharmacy use the same chit engine with different fields and rules, so the product behaves differently for each without being a different product. That is the whole idea.', NULL, '{"type":"img","src":"app/assets/usecase-compare.png","caption":"Same chit, two schemas — example coming."}'::jsonb, 170)
  ON CONFLICT (id) DO UPDATE SET context=EXCLUDED.context, topics=EXCLUDED.topics, question=EXCLUDED.question, answer=EXCLUDED.answer, fit=EXCLUDED.fit, media=EXCLUDED.media, sort=EXCLUDED.sort, active=true, updated_at=now();
INSERT INTO assist_qa (id, context, topics, question, answer, fit, media, sort) VALUES ('ca_assign', ARRAY['coassists']::text[], ARRAY['assign','push','pull','give work','distribute','bulk','queue','pool']::text[], 'How do I give work to a co-assist?', 'Two ways: PUSH (you hand a chit to a specific co-assist) or PULL (they take from the shared pool themselves). You can also bulk-assign several chits at once. Either way the chit stays the same shared record — assignment just decides who works it.', NULL, NULL, 180)
  ON CONFLICT (id) DO UPDATE SET context=EXCLUDED.context, topics=EXCLUDED.topics, question=EXCLUDED.question, answer=EXCLUDED.answer, fit=EXCLUDED.fit, media=EXCLUDED.media, sort=EXCLUDED.sort, active=true, updated_at=now();
INSERT INTO assist_qa (id, context, topics, question, answer, fit, media, sort) VALUES ('ca_scope', ARRAY['coassists']::text[], ARRAY['limit','scope','access','permission','restrict','what can they do','control']::text[], 'Can I limit what a co-assist can do?', 'A co-assist always acts inside YOUR entity''s scope — never another business''s work. Being honest: per-actor limits (restricting one co-assist to only some of your chits) are planned, NOT yet enforced — today a co-assist can see all of your entity''s chits. Entity-level isolation is solid; finer per-actor scoping is coming.', NULL, NULL, 190)
  ON CONFLICT (id) DO UPDATE SET context=EXCLUDED.context, topics=EXCLUDED.topics, question=EXCLUDED.question, answer=EXCLUDED.answer, fit=EXCLUDED.fit, media=EXCLUDED.media, sort=EXCLUDED.sort, active=true, updated_at=now();
INSERT INTO assist_qa (id, context, topics, question, answer, fit, media, sort) VALUES ('ca_break', ARRAY['coassists']::text[], ARRAY['break','leave','absent','off','holiday','reassign','return','shift']::text[], 'What happens when a co-assist takes a break or leaves?', 'Their open work returns to the shared pool so nothing is stranded, and the move is recorded. They sign in with a username and PIN and can work shifts; when they are away, others (or you) can pick the work up.', NULL, NULL, 200)
  ON CONFLICT (id) DO UPDATE SET context=EXCLUDED.context, topics=EXCLUDED.topics, question=EXCLUDED.question, answer=EXCLUDED.answer, fit=EXCLUDED.fit, media=EXCLUDED.media, sort=EXCLUDED.sort, active=true, updated_at=now();
INSERT INTO assist_qa (id, context, topics, question, answer, fit, media, sort) VALUES ('ca_nonhuman', ARRAY['coassists']::text[], ARRAY['machine','connector','device','iot','erp','agent','ai','robot','non-human','system','automate']::text[], 'Can a machine or system be a co-assist?', 'That is the direction — connectors, devices, process rules and AI agents as participant types that act for you. Being honest: today co-assists are people. The model is built to add non-human participants next, but they are not live yet.', NULL, NULL, 210)
  ON CONFLICT (id) DO UPDATE SET context=EXCLUDED.context, topics=EXCLUDED.topics, question=EXCLUDED.question, answer=EXCLUDED.answer, fit=EXCLUDED.fit, media=EXCLUDED.media, sort=EXCLUDED.sort, active=true, updated_at=now();
INSERT INTO assist_qa (id, context, topics, question, answer, fit, media, sort) VALUES ('sc_what', ARRAY['schema','compose','register']::text[], ARRAY['schema','blueprint','what is','fields','template','structure','deal contains']::text[], 'What is a schema (blueprint)?', 'The schema is what a deal CONTAINS — its fields and rules (e.g. subject, delivery, note, line items). The trustworthy container around it (the sealed record, your privacy, the audit trail) is fixed; the schema is the part you shape to your business.', NULL, NULL, 220)
  ON CONFLICT (id) DO UPDATE SET context=EXCLUDED.context, topics=EXCLUDED.topics, question=EXCLUDED.question, answer=EXCLUDED.answer, fit=EXCLUDED.fit, media=EXCLUDED.media, sort=EXCLUDED.sort, active=true, updated_at=now();
INSERT INTO assist_qa (id, context, topics, question, answer, fit, media, sort) VALUES ('sc_fields', ARRAY['schema','compose','register']::text[], ARRAY['change fields','add field','edit schema','customize','configure','my fields','rules']::text[], 'How do I change what a deal carries?', 'You configure the schema — add or change the fields and rules a chit type uses. The same engine then renders those fields wherever you compose. It is configuration, so the behaviour follows your definition without a rebuild.', NULL, NULL, 230)
  ON CONFLICT (id) DO UPDATE SET context=EXCLUDED.context, topics=EXCLUDED.topics, question=EXCLUDED.question, answer=EXCLUDED.answer, fit=EXCLUDED.fit, media=EXCLUDED.media, sort=EXCLUDED.sort, active=true, updated_at=now();
INSERT INTO assist_qa (id, context, topics, question, answer, fit, media, sort) VALUES ('sc_nodev', ARRAY['schema','compose','register']::text[], ARRAY['developer','code','coding','technical','set up myself','no code','without developer']::text[], 'Do I need a developer to set up my schema?', 'No. The schema is configuration, not code — you define the fields and rules your deals carry and the same engine adapts. The engineering that has to be right (privacy, the honest record, safe failure) is already built into the container.', NULL, NULL, 240)
  ON CONFLICT (id) DO UPDATE SET context=EXCLUDED.context, topics=EXCLUDED.topics, question=EXCLUDED.question, answer=EXCLUDED.answer, fit=EXCLUDED.fit, media=EXCLUDED.media, sort=EXCLUDED.sort, active=true, updated_at=now();
INSERT INTO assist_qa (id, context, topics, question, answer, fit, media, sort) VALUES ('sc_seal', ARRAY['schema','compose']::text[], ARRAY['change schema','old chits','existing','past deals','history','versions','what happens']::text[], 'If I change my schema, what about existing chits?', 'Each chit is SEALED with the fields it carried when it was made — that snapshot stays on the record, so your history is never rewritten. Schema changes shape NEW chits going forward. The sealed, time-stamped record is the point.', NULL, NULL, 250)
  ON CONFLICT (id) DO UPDATE SET context=EXCLUDED.context, topics=EXCLUDED.topics, question=EXCLUDED.question, answer=EXCLUDED.answer, fit=EXCLUDED.fit, media=EXCLUDED.media, sort=EXCLUDED.sort, active=true, updated_at=now();
INSERT INTO assist_qa (id, context, topics, question, answer, fit, media, sort) VALUES ('sc_examples', ARRAY['schema','compose','register']::text[], ARRAY['example','timber','pharma','services','how different','vertical','industry']::text[], 'How do schemas differ across businesses?', 'Same engine, different fields. A timber yard carries item/quantity/delivery yard; a pharmacy can require batch and expiry; a services firm carries scope and milestones instead of line-item prices. One product, your schema.', NULL, NULL, 260)
  ON CONFLICT (id) DO UPDATE SET context=EXCLUDED.context, topics=EXCLUDED.topics, question=EXCLUDED.question, answer=EXCLUDED.answer, fit=EXCLUDED.fit, media=EXCLUDED.media, sort=EXCLUDED.sort, active=true, updated_at=now();
INSERT INTO assist_qa (id, context, topics, question, answer, fit, media, sort) VALUES ('ca_access', ARRAY['coassists']::text[], ARRAY['access','grant','scope','network','node','permission','where']::text[], 'Where does a co-assist''s access come from?', 'You can only grant what you hold; access flows down the Network tree and is checked live. Set participants here; their scope ties to their node in Network.', NULL, NULL, 270)
  ON CONFLICT (id) DO UPDATE SET context=EXCLUDED.context, topics=EXCLUDED.topics, question=EXCLUDED.question, answer=EXCLUDED.answer, fit=EXCLUDED.fit, media=EXCLUDED.media, sort=EXCLUDED.sort, active=true, updated_at=now();
INSERT INTO assist_qa (id, context, topics, question, answer, fit, media, sort) VALUES ('tk_what', ARRAY['task']::text[], ARRAY['task','received','inbox','lands']::text[], 'What lands in Task?', 'Every chit a counterparty addresses TO you — orders to fulfil, queries to answer, disputes to resolve. It''s your received inbox; Order is the sent side.', NULL, NULL, 280)
  ON CONFLICT (id) DO UPDATE SET context=EXCLUDED.context, topics=EXCLUDED.topics, question=EXCLUDED.question, answer=EXCLUDED.answer, fit=EXCLUDED.fit, media=EXCLUDED.media, sort=EXCLUDED.sort, active=true, updated_at=now();
INSERT INTO assist_qa (id, context, topics, question, answer, fit, media, sort) VALUES ('tk_act', ARRAY['task']::text[], ARRAY['act','advance','status','assign','message','dispute']::text[], 'How do I act on a task?', 'Open it to advance its status (open → in progress → closed), assign it to a co-assist, message the other party, or raise/resolve a dispute. Each action is recorded on the shared chit.', NULL, NULL, 290)
  ON CONFLICT (id) DO UPDATE SET context=EXCLUDED.context, topics=EXCLUDED.topics, question=EXCLUDED.question, answer=EXCLUDED.answer, fit=EXCLUDED.fit, media=EXCLUDED.media, sort=EXCLUDED.sort, active=true, updated_at=now();
INSERT INTO assist_qa (id, context, topics, question, answer, fit, media, sort) VALUES ('tk_vs', ARRAY['task','order']::text[], ARRAY['task','order','difference','copies']::text[], 'Task vs Order?', 'Same chit, two copies: the receiver''s copy sits in Task, the sender''s in Order. Each side carries its own status — the Chit & Bridge two-copy model.', NULL, NULL, 300)
  ON CONFLICT (id) DO UPDATE SET context=EXCLUDED.context, topics=EXCLUDED.topics, question=EXCLUDED.question, answer=EXCLUDED.answer, fit=EXCLUDED.fit, media=EXCLUDED.media, sort=EXCLUDED.sort, active=true, updated_at=now();
INSERT INTO assist_qa (id, context, topics, question, answer, fit, media, sort) VALUES ('tk_pri', ARRAY['task']::text[], ARRAY['priority','flag','urgent','queue']::text[], 'Why is one flagged priority?', 'A ⚑ means the customer flagged it, or you re-prioritised it. Priority is internal routing in your queue — it doesn''t change the other party''s copy.', NULL, NULL, 310)
  ON CONFLICT (id) DO UPDATE SET context=EXCLUDED.context, topics=EXCLUDED.topics, question=EXCLUDED.question, answer=EXCLUDED.answer, fit=EXCLUDED.fit, media=EXCLUDED.media, sort=EXCLUDED.sort, active=true, updated_at=now();
INSERT INTO assist_qa (id, context, topics, question, answer, fit, media, sort) VALUES ('or_what', ARRAY['order']::text[], ARRAY['order','sent','authored','bridged']::text[], 'What''s in Order?', 'Chits you''ve sent — your copy of each deal you originated. Self-chits show both here and in Task; drafts stay here until bridged.', NULL, NULL, 320)
  ON CONFLICT (id) DO UPDATE SET context=EXCLUDED.context, topics=EXCLUDED.topics, question=EXCLUDED.question, answer=EXCLUDED.answer, fit=EXCLUDED.fit, media=EXCLUDED.media, sort=EXCLUDED.sort, active=true, updated_at=now();
INSERT INTO assist_qa (id, context, topics, question, answer, fit, media, sort) VALUES ('or_self', ARRAY['order']::text[], ARRAY['send','myself','self-chit']::text[], 'Can I send an order to myself?', 'Yes — a self-chit. It lands once in Order (sent) and once in Task (received), same thread, each with its own status.', NULL, NULL, 330)
  ON CONFLICT (id) DO UPDATE SET context=EXCLUDED.context, topics=EXCLUDED.topics, question=EXCLUDED.question, answer=EXCLUDED.answer, fit=EXCLUDED.fit, media=EXCLUDED.media, sort=EXCLUDED.sort, active=true, updated_at=now();
INSERT INTO assist_qa (id, context, topics, question, answer, fit, media, sort) VALUES ('or_start', ARRAY['order']::text[], ARRAY['start','compose','new order','send-as']::text[], 'How do I start an order?', 'Use Compose — pick Send-as (entity or actor), To (self or a counterparty), add catalogue line items, then Send.', NULL, NULL, 340)
  ON CONFLICT (id) DO UPDATE SET context=EXCLUDED.context, topics=EXCLUDED.topics, question=EXCLUDED.question, answer=EXCLUDED.answer, fit=EXCLUDED.fit, media=EXCLUDED.media, sort=EXCLUDED.sort, active=true, updated_at=now();
INSERT INTO assist_qa (id, context, topics, question, answer, fit, media, sort) VALUES ('sp_add', ARRAY['suppliers']::text[], ARRAY['add','supplier','user id','pull catalogue']::text[], 'How do I add a supplier?', 'Enter the supplier''s User ID (8+ characters or email) and add them. They appear here so you can pull their catalogue into an order.', NULL, NULL, 350)
  ON CONFLICT (id) DO UPDATE SET context=EXCLUDED.context, topics=EXCLUDED.topics, question=EXCLUDED.question, answer=EXCLUDED.answer, fit=EXCLUDED.fit, media=EXCLUDED.media, sort=EXCLUDED.sort, active=true, updated_at=now();
INSERT INTO assist_qa (id, context, topics, question, answer, fit, media, sort) VALUES ('sp_branch', ARRAY['suppliers']::text[], ARRAY['supplier','branch','network','connection']::text[], 'Supplier or branch?', 'A supplier is a different business you buy from — a Connection. A branch is part of your own business — Network. Same language, different relationship.', NULL, NULL, 360)
  ON CONFLICT (id) DO UPDATE SET context=EXCLUDED.context, topics=EXCLUDED.topics, question=EXCLUDED.question, answer=EXCLUDED.answer, fit=EXCLUDED.fit, media=EXCLUDED.media, sort=EXCLUDED.sort, active=true, updated_at=now();
INSERT INTO assist_qa (id, context, topics, question, answer, fit, media, sort) VALUES ('cat_for', ARRAY['catalogue']::text[], ARRAY['catalogue','products','prices','storefront']::text[], 'What''s the catalogue for?', 'It''s your products and prices. Compose pulls line items from it, and a public catalogue is what customers see in your storefront.', NULL, NULL, 370)
  ON CONFLICT (id) DO UPDATE SET context=EXCLUDED.context, topics=EXCLUDED.topics, question=EXCLUDED.question, answer=EXCLUDED.answer, fit=EXCLUDED.fit, media=EXCLUDED.media, sort=EXCLUDED.sort, active=true, updated_at=now();
INSERT INTO assist_qa (id, context, topics, question, answer, fit, media, sort) VALUES ('cat_vis', ARRAY['catalogue']::text[], ARRAY['visible','customers','public','private','restricted']::text[], 'Is my catalogue visible to customers?', 'Only if you make it public. A catalogue is private by default; visibility is private / restricted / public, set per schema.', NULL, NULL, 380)
  ON CONFLICT (id) DO UPDATE SET context=EXCLUDED.context, topics=EXCLUDED.topics, question=EXCLUDED.question, answer=EXCLUDED.answer, fit=EXCLUDED.fit, media=EXCLUDED.media, sort=EXCLUDED.sort, active=true, updated_at=now();
INSERT INTO assist_qa (id, context, topics, question, answer, fit, media, sort) VALUES ('dp_freeze', ARRAY['disputes']::text[], ARRAY['dispute','freeze','lock','complete','delete']::text[], 'Does a dispute freeze the chit?', 'No — it''s a flag, not a lock. The lifecycle continues, but the chit can''t be deleted while a dispute is open, and it won''t complete until the dispute is resolved.', NULL, NULL, 390)
  ON CONFLICT (id) DO UPDATE SET context=EXCLUDED.context, topics=EXCLUDED.topics, question=EXCLUDED.question, answer=EXCLUDED.answer, fit=EXCLUDED.fit, media=EXCLUDED.media, sort=EXCLUDED.sort, active=true, updated_at=now();
INSERT INTO assist_qa (id, context, topics, question, answer, fit, media, sort) VALUES ('dp_resolve', ARRAY['disputes']::text[], ARRAY['resolve','raiser','note','who']::text[], 'Who can resolve a dispute?', 'The party who raised it resolves it, and a resolution note is required. Disputes against you wait on the raiser.', NULL, NULL, 400)
  ON CONFLICT (id) DO UPDATE SET context=EXCLUDED.context, topics=EXCLUDED.topics, question=EXCLUDED.question, answer=EXCLUDED.answer, fit=EXCLUDED.fit, media=EXCLUDED.media, sort=EXCLUDED.sort, active=true, updated_at=now();
INSERT INTO assist_qa (id, context, topics, question, answer, fit, media, sort) VALUES ('mis_src', ARRAY['mis']::text[], ARRAY['mis','numbers','computed','rollup']::text[], 'Where do the MIS numbers come from?', 'They''re computed live from your chits, disputes, co-assists and suppliers — a client-side roll-up, not a separate report you maintain.', NULL, NULL, 410)
  ON CONFLICT (id) DO UPDATE SET context=EXCLUDED.context, topics=EXCLUDED.topics, question=EXCLUDED.question, answer=EXCLUDED.answer, fit=EXCLUDED.fit, media=EXCLUDED.media, sort=EXCLUDED.sort, active=true, updated_at=now();
INSERT INTO assist_qa (id, context, topics, question, answer, fit, media, sort) VALUES ('pf_uid', ARRAY['profile']::text[], ARRAY['user id','identity','bridge id','external']::text[], 'What''s my User ID?', 'Your external identity — an 8+ character id or your email. Others connect to you by it. Your internal bridge_id is plumbing and isn''t shown.', NULL, NULL, 420)
  ON CONFLICT (id) DO UPDATE SET context=EXCLUDED.context, topics=EXCLUDED.topics, question=EXCLUDED.question, answer=EXCLUDED.answer, fit=EXCLUDED.fit, media=EXCLUDED.media, sort=EXCLUDED.sort, active=true, updated_at=now();
INSERT INTO assist_qa (id, context, topics, question, answer, fit, media, sort) VALUES ('pf_shop', ARRAY['profile']::text[], ARRAY['shop status','open','closed','away']::text[], 'What is shop status?', 'Your customer-facing open sign — open, closed or away — separate from account status and catalogue visibility.', NULL, NULL, 430)
  ON CONFLICT (id) DO UPDATE SET context=EXCLUDED.context, topics=EXCLUDED.topics, question=EXCLUDED.question, answer=EXCLUDED.answer, fit=EXCLUDED.fit, media=EXCLUDED.media, sort=EXCLUDED.sort, active=true, updated_at=now();
INSERT INTO assist_qa (id, context, topics, question, answer, fit, media, sort) VALUES ('st_model', ARRAY['settings']::text[], ARRAY['pull','push','both','assignment','route']::text[], 'Pull, push or both?', 'Pull lets co-assists take tasks; push assigns to them; both allows either. It sets how work reaches your team.', NULL, NULL, 440)
  ON CONFLICT (id) DO UPDATE SET context=EXCLUDED.context, topics=EXCLUDED.topics, question=EXCLUDED.question, answer=EXCLUDED.answer, fit=EXCLUDED.fit, media=EXCLUDED.media, sort=EXCLUDED.sort, active=true, updated_at=now();
INSERT INTO assist_qa (id, context, topics, question, answer, fit, media, sort) VALUES ('st_max', ARRAY['settings']::text[], ARRAY['max tasks','load','ceiling']::text[], 'What''s max tasks per actor?', 'A load ceiling per co-assist, so no one is over-assigned. Combined with shift status, it shapes routing.', NULL, NULL, 450)
  ON CONFLICT (id) DO UPDATE SET context=EXCLUDED.context, topics=EXCLUDED.topics, question=EXCLUDED.question, answer=EXCLUDED.answer, fit=EXCLUDED.fit, media=EXCLUDED.media, sort=EXCLUDED.sort, active=true, updated_at=now();
INSERT INTO assist_qa (id, context, topics, question, answer, fit, media, sort) VALUES ('cmp_self', ARRAY['compose']::text[], ARRAY['self-chit','author','bridge','own record']::text[], 'What is a self-chit?', 'Compose creates a self-chit — you author your own record first. It becomes a shared truth the moment you bridge it (address it to a counterparty). With no counterparty it''s your own record / draft.', NULL, NULL, 460)
  ON CONFLICT (id) DO UPDATE SET context=EXCLUDED.context, topics=EXCLUDED.topics, question=EXCLUDED.question, answer=EXCLUDED.answer, fit=EXCLUDED.fit, media=EXCLUDED.media, sort=EXCLUDED.sort, active=true, updated_at=now();
INSERT INTO assist_qa (id, context, topics, question, answer, fit, media, sort) VALUES ('cmp_two', ARRAY['compose']::text[], ARRAY['two copies','order','task','thread']::text[], 'Why two copies?', 'Every party keeps its own copy. Address a chit to yourself and it lands as one copy in Order (sent) and one in Task (received) — same thread, each with its own status.', NULL, NULL, 470)
  ON CONFLICT (id) DO UPDATE SET context=EXCLUDED.context, topics=EXCLUDED.topics, question=EXCLUDED.question, answer=EXCLUDED.answer, fit=EXCLUDED.fit, media=EXCLUDED.media, sort=EXCLUDED.sort, active=true, updated_at=now();
INSERT INTO assist_qa (id, context, topics, question, answer, fit, media, sort) VALUES ('cmp_as', ARRAY['compose']::text[], ARRAY['send as','entity','actor','author']::text[], 'Send as entity or actor?', 'You can author as the entity itself or as one of its co-assists (actors). Both can author and self-address; the mechanism is identical. The actor acts FOR the entity, which stays the party.', NULL, NULL, 480)
  ON CONFLICT (id) DO UPDATE SET context=EXCLUDED.context, topics=EXCLUDED.topics, question=EXCLUDED.question, answer=EXCLUDED.answer, fit=EXCLUDED.fit, media=EXCLUDED.media, sort=EXCLUDED.sort, active=true, updated_at=now();
INSERT INTO assist_qa (id, context, topics, question, answer, fit, media, sort) VALUES ('cmp_items', ARRAY['compose']::text[], ARRAY['line items','catalogue','picker','quantity','price']::text[], 'Where do line items come from?', 'Items are picked from your catalogue, not free-typed — pick a product, set the quantity; price flows from the catalogue and the total computes.', NULL, NULL, 490)
  ON CONFLICT (id) DO UPDATE SET context=EXCLUDED.context, topics=EXCLUDED.topics, question=EXCLUDED.question, answer=EXCLUDED.answer, fit=EXCLUDED.fit, media=EXCLUDED.media, sort=EXCLUDED.sort, active=true, updated_at=now();
INSERT INTO assist_qa (id, context, topics, question, answer, fit, media, sort) VALUES ('cmp_draft', ARRAY['compose']::text[], ARRAY['draft','unsent','save','bridge']::text[], 'What''s a draft?', 'A draft is the un-sent state before bridging. Save as draft keeps your authored chit privately; sending it — to self or a counterparty — makes it real and fans out the copies.', NULL, NULL, 500)
  ON CONFLICT (id) DO UPDATE SET context=EXCLUDED.context, topics=EXCLUDED.topics, question=EXCLUDED.question, answer=EXCLUDED.answer, fit=EXCLUDED.fit, media=EXCLUDED.media, sort=EXCLUDED.sort, active=true, updated_at=now();
INSERT INTO assist_qa (id, context, topics, question, answer, fit, media, sort) VALUES ('cmp_fields', ARRAY['compose']::text[], ARRAY['fields','schema','subject','delivery','note']::text[], 'Where do the compose fields come from?', 'Compose renders from your entity''s schema — the fields your chit type carries (subject, delivery, note) plus your line items.', NULL, NULL, 510)
  ON CONFLICT (id) DO UPDATE SET context=EXCLUDED.context, topics=EXCLUDED.topics, question=EXCLUDED.question, answer=EXCLUDED.answer, fit=EXCLUDED.fit, media=EXCLUDED.media, sort=EXCLUDED.sort, active=true, updated_at=now();
